// <auto-generated />
using System;
using CozyCinema.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CozyCinema.Infrastructure.Migrations
{
    [DbContext(typeof(CozyCinemaDbContext))]
    [Migration("20260916112843_AddVotingRoundCreatedAt")]
    partial class AddVotingRoundCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CozyCinema.Domain.Entities.RoundMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("SuggestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TmdbMovieId")
                        .HasColumnType("integer");

                    b.Property<Guid>("VotingRoundId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SuggestedByUserId");

                    b.HasIndex("VotingRoundId");

                    b.ToTable("RoundMovies");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentMovieCoverUrl")
                        .HasColumnType("text");

                    b.Property<string>("CurrentMovieTitle")
                        .HasColumnType("text");

                    b.Property<int?>("CurrentMovieTmdbId")
                        .HasColumnType("integer");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid?>("LastPickerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("LastPickerUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.SessionMember", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("SessionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SessionMembers");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoundMovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoundMovieId", "UserId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.VotingRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerMovieId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("WinnerMovieId");

                    b.ToTable("VotingRounds");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.WatchedMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .HasColumnType("text");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TmdbMovieId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchedMovies");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.RoundMovie", b =>
                {
                    b.HasOne("CozyCinema.Domain.Entities.User", "SuggestedByUser")
                        .WithMany()
                        .HasForeignKey("SuggestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CozyCinema.Domain.Entities.VotingRound", "VotingRound")
                        .WithMany("Movies")
                        .HasForeignKey("VotingRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuggestedByUser");

                    b.Navigation("VotingRound");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.Session", b =>
                {
                    b.HasOne("CozyCinema.Domain.Entities.User", "LastPicker")
                        .WithMany()
                        .HasForeignKey("LastPickerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastPicker");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.SessionMember", b =>
                {
                    b.HasOne("CozyCinema.Domain.Entities.Session", "Session")
                        .WithMany("Members")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozyCinema.Domain.Entities.User", "User")
                        .WithMany("SessionMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.Vote", b =>
                {
                    b.HasOne("CozyCinema.Domain.Entities.RoundMovie", "RoundMovie")
                        .WithMany("Votes")
                        .HasForeignKey("RoundMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozyCinema.Domain.Entities.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoundMovie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.VotingRound", b =>
                {
                    b.HasOne("CozyCinema.Domain.Entities.Session", "Session")
                        .WithMany("VotingRounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozyCinema.Domain.Entities.RoundMovie", "WinnerMovie")
                        .WithMany()
                        .HasForeignKey("WinnerMovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Session");

                    b.Navigation("WinnerMovie");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.WatchedMovie", b =>
                {
                    b.HasOne("CozyCinema.Domain.Entities.Session", "Session")
                        .WithMany("WatchedMovies")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozyCinema.Domain.Entities.User", "User")
                        .WithMany("WatchedMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.RoundMovie", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.Session", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("VotingRounds");

                    b.Navigation("WatchedMovies");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.User", b =>
                {
                    b.Navigation("SessionMemberships");

                    b.Navigation("Votes");

                    b.Navigation("WatchedMovies");
                });

            modelBuilder.Entity("CozyCinema.Domain.Entities.VotingRound", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
